// <auto-generated />
using System;
using EliosPaymentService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EliosPaymentService.Migrations
{
    [DbContext(typeof(CVBuilderDataContext))]
    [Migration("20251126120607_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EliosPaymentService.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountRemaining")
                        .HasColumnType("bigint");

                    b.Property<string>("Bin")
                        .HasColumnType("text");

                    b.Property<string>("BuyerAddress")
                        .HasColumnType("text");

                    b.Property<string>("BuyerCompanyName")
                        .HasColumnType("text");

                    b.Property<string>("BuyerEmail")
                        .HasColumnType("text");

                    b.Property<string>("BuyerName")
                        .HasColumnType("text");

                    b.Property<bool?>("BuyerNotGetInvoice")
                        .HasColumnType("boolean");

                    b.Property<string>("BuyerPhone")
                        .HasColumnType("text");

                    b.Property<string>("CancelUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastTransactionUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentLinkId")
                        .HasColumnType("text");

                    b.Property<string>("QrCode")
                        .HasColumnType("text");

                    b.Property<string>("ReturnUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TaxPercentage")
                        .HasColumnType("integer");

                    b.Property<long>("TotalAmount")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EliosPaymentService.Models.OrderInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeOfTax")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("IssuedDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("IssuedTimestamp")
                        .HasColumnType("bigint");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReservationCode")
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderInvoices");
                });

            modelBuilder.Entity("EliosPaymentService.Models.OrderTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("CounterAccountBankId")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountBankName")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountName")
                        .HasColumnType("text");

                    b.Property<string>("CounterAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentLinkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TransactionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VirtualAccountName")
                        .HasColumnType("text");

                    b.Property<string>("VirtualAccountNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderTransactions");
                });

            modelBuilder.Entity("EliosPaymentService.Models.Transfer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ApprovalState")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayoutId")
                        .HasColumnType("text");

                    b.Property<int?>("TotalCredit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("EliosPaymentService.Models.TransferTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("PayoutTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("ToAccountName")
                        .HasColumnType("text");

                    b.Property<string>("ToAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToBin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("TransactionDatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.ToTable("TransferTransactions");
                });

            modelBuilder.Entity("EliosPaymentService.Models.Order", b =>
                {
                    b.OwnsMany("EliosPaymentService.Models.OrderItem", "Items", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .HasColumnType("text");

                            b1.Property<long>("Price")
                                .HasColumnType("bigint");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.Property<int?>("TaxPercentage")
                                .HasColumnType("integer");

                            b1.Property<string>("Unit")
                                .HasColumnType("text");

                            b1.HasKey("OrderId", "Name");

                            b1.ToTable("OrderItems", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Items");
                });

            modelBuilder.Entity("EliosPaymentService.Models.TransferTransaction", b =>
                {
                    b.HasOne("EliosPaymentService.Models.Transfer", null)
                        .WithMany("Transactions")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EliosPaymentService.Models.Transfer", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
